//
// Created by Ivan Yakovenko on 22.06.2024.
//

#ifndef ASSIGNMENT_4_PROGRAMMING_PARADIGMS_TEXTEDITOR_H
#define ASSIGNMENT_4_PROGRAMMING_PARADIGMS_TEXTEDITOR_H


class TextEditor {

};


#endif //ASSIGNMENT_4_PROGRAMMING_PARADIGMS_TEXTEDITOR_H
